// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table TempbronzeRawCommonData (version:string, siteId:string, sendTimestamp:datetime, oem:string, site:dynamic, devices:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-merge table TempCopiedTable (type:string, siteId:string, version:string, oem:string, sendTimestamp:string, site:dynamic, devices:dynamic, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
